README.md, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java
- Concurrent 패키지에 대해 공부하며 Java에서 멀티스레딩을 어떻게 사용하는지 파악했습니다. 
전에 쓰던 파이썬에선 GIL로 인해 주로 멀티프로세싱을 이용했었는데, Java는 멀티스레딩이 주로 활용되어 메모리 측면에서 효율적일 듯 합니다.
- index.html이 반환되긴 하는데, 표시가 제대로 되지 않습니다. 아마 MIME 타입을 제대로 지키지 않아 생긴 문제인 듯 한데, step3에 관련된 내용이 있는 듯 하여 step3에서 수정할 듯 합니다.
- C언어로 순수 TCP 소켓통신 기반 게임 서버를 구현했던 적이 있는데, 그와 거의 동일한 것 같습니다.(당연한 것이겠지만요...) 처음 걱정만큼 생각보다 어렵진 않았던 것 같습니다.
- HTTP를 직접 분해해서 작업해보니 HTTP 구조를 확실히 알 듯 합니다.
=> [정성태] step-1 index.html 응답

src/main/java/controller/Controller.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java
index.html 파일을 응답할 수 있게 구현했습니다.
ExctorService 인터페이스를 활용해서 코드를 수정했습니다.
runnable 인터페이스의 한계에 대해서 알게되어 callable, future와 같은 인터페이스를 찾아보았습니다.
=> [이용재] step - 1 index.html 응답

README.md, build.gradle, src/main/java/db/Database.java, src/main/java/model/User.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/exception/InvalidRequestException.java, src/main/java/webserver/utils/HttpUtil.java, src/main/java/webserver/utils/view/Extension.java, src/main/java/webserver/utils/view/FileUtil.java, src/test/java/webserver/utils/HttpUtilTest.java, src/test/java/webserver/utils/view/FileUtilTest.java, src/test/java/webserver/view/ViewResolverTest.java
- 정적인 html 파일 응답
- HTTP Request 내용 출력
- Thread pool 적용
- 입출력 버퍼링을 통해 얼마만큼의 성능 개선을 가져갈 수 있을까?
- 현재는 요청에 따라 소켓과 스레드가 생성/종료된다. 이는 매우 비효율적이기에 스레드 풀을 적용하고자 하였고, 이 과정에서 어느 종류의 스레드 풀이 적합할지에 대해 고민했다. 그리고 그 결과, 가장 보편적이라 할 수 있는  FixedThreadPool의 사용이 적합하다고 판단했다.
- 추후에 Body까지 받아야 하는 상황에서는 Content-length를 고려해서 Http 메세지를 받아야한다. 이 부분을 어떻게 구현하면 좋을까?
- wire shark로 패킷캡쳐링이 가능하다. 실제 요청/응답이 궁금하다면 사용하도록 하자
- 스레드풀중에 WorkStealingThreadPool 이란것이 존재함을 이후에 알게되었다. 해당 스레드풀의 특성을 확인해보자
=> [장동호] step-1 index.html 응답

README.md, src/main/java/controller/Controller.java, src/main/java/controller/ForwardController.java, src/main/java/controller/HomeController.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/HttpRequest.java, src/main/java/webserver/HttpResponse.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/RequestMapping.java, src/main/java/webserver/WebServer.java
- concurrent 패키지가 이런 식으로 작성하면 제대로 적용된 것이 맞는지?? 이에 대한 검증은 어떻게 할 수 있는지
- 테스트 케이스는 어떤 식으로 짤 수 있는지?
=> [신희을] step-1 index.html 응답

README.md, src/main/java/constant/SourcePath.java, src/main/java/constant/Uri.java, src/main/java/controller/RestController.java, src/main/java/model/HttpHeader.java, src/main/java/model/HttpRequest.java, src/main/java/model/HttpResponse.java, src/main/java/model/RequestUri.java, src/main/java/model/enums/HttpStatusCode.java, src/main/java/model/enums/Method.java, src/main/java/service/FileService.java, src/main/java/service/ResponseService.java, src/main/java/util/Parser.java, src/main/java/util/StringUtils.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java
- concurrent, 동시성과 병렬성 wiki에 내용 정리
- Request, Response, Header, URI 등등 클래스 생성
- RequestUri 
- Rest API를 처리하는 RestController 생성
- Thread 객체 concurrent.Executor로 리팩토링
- 404 페이지, 400 페이지 에러 처리
- 처음엔 URI만 HttpRequest field로 만들었는데, request parameter도 들어올 수 있기 때문에 같이 처리하였다. 따로 RequestUri 클래스로 캡슐화 진행했다.
- 깡 java로 서버 작업이 처음이었기 때문에 한 번에 코드를 이해하지 못했다. 세션 시간에 다른 분들의 코드를 보고 나서야 감잡을 수 있었다. 
- request로 들어온 헤더를 그대로 response에 사용할까 고민했었다. 하지만 request 안에 노출되면 좋지 않을 것(authorization 같은 것들)들이 있을 것이라 생각해서 간단하게 헤더를 만들었다. 헤더 생성 부분을 더 좋게 처리할 방법을 고민하고 있다.
- java 라이브러리로 기본적으로 제공하는 Http Status Code enum 클래스가 없는 것 같다. static 으론 제공하지만 "OK" 같은 메시지를 남길 수 없어서 enum 클래스를 직접 만들어서 사용했다. (그런데 이제 구현은 스택오버플로우에서 된)
- HttpHeader 생성자가 인자가 많아서 builder 패턴을 적용할 예정이다.
=> [박선미] step-1 index.html 응답

README.md, src/main/java/db/Database.java, src/main/java/webserver/HttpWasRequest.java, src/main/java/webserver/HttpWasResponse.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/test/java/webserver/HttpWasRequestTest.java
- index.html을 반환할때, css 및 다른곳들은 왜 오류가 나는지 몰라 걱정했다
- 확인을해보니 경로가 없어서 나는 문제였다
- Thread를 잘 쓰고 있는가? 라는 곳에서 확신이 들지 않았다. 기존 `forkJoinPool`은 코어 갯수에 따라서 자동으로 Thread를 관리하는데 용도가 맞지 않은것 같아 `FixedThreadPool`을 사용했다
- 테스트코드를 어디까지 할지? 잘 어떻게 작성해야할지 고민이 크다...
=> [유해찬] step-1 index.html 응답

src/main/java/annotation/RequestMappingHandler.java, src/main/java/controller/Controller.java, src/main/java/db/Database.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpResponse.java, src/main/java/http/Mime.java, src/main/java/webserver/RequestHandler.java, src/test/java/controller/ControllerTest.java, src/test/java/db/DatabaseTest.java, src/test/java/http/HttpRequestTest.java
- Mime 타입을 구현해서 http response의 content-type에 적용
- soft assertion 적용
- Database find에 Optional 적용
- Mime type의 변환은 HttpRequest의 역할인가? HttpResponse의 역할인가?
=> [한도현] step-3 다양한 컨텐츠 타입 지원

src/main/java/service/FileService.java, src/main/java/service/UserService.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/model/Request.java, src/main/java/webserver/model/Response.java, src/test/java/service/FileServiceTest.java, src/test/java/service/UserServiceTest.java, src/test/java/webserver/RequestHandlerTest.java
RequestHandler측에 과도하게 책임이 존재하는 듯 하여 비즈니스 로직등은 service 패키지로 분할하였다. Database나 Model 자체에 로직을 두는 것도 괜찮을까 했지만, 둘 다 최소한의 일만 해야 한다 생각하여 위와 같이 구성했다. 정답이 있는 문제인지 잘 모르겠다.
=> [정성태] step-3 다양한 컨텐츠 타입 지원

docs/README1.md, src/main/java/util/HttpRequestUtils.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java
- HTTP, Thread, Concurrent 공부한 내용 Git Wiki에 정리
- Request Header 전체 출력
- Request Header에서 경로를 추출해 http://localhost:8080/index.html로 접속했을 때 index.html 파일을 읽어 응답하도록 구현
- HttpRequestUtils 클래스를 만들어 Request에 관한 부분을 메소드화해서 분리
- Thread로 구현되어 있던 코드를 여러번 요청하는 경우 매번 스레드를 생성하는 비효율을 없애고자 newWorkStealingPool을 이용해 스레드 풀 구현
- 어떤 스레드 풀을 사용해야 효율적인 멀티 스레딩 프로그래밍이 가능할지 고민해봄 => newWorkStealingPool을 사용
- newWorkStealingPool을 사용한 이유는 사용 가능한 CPU 코어를 사용해 병렬 처리를 하도록 하고 여러 Queue를 사용해 경합을 줄이기 때문
- newWorkStealingPool이 지원할 parallelism을 어떻게 설정해야할지 고민 중!
=> [김정연] step-1 index.html 응답

README.md, src/main/java/utils/StaticFIleUtils.java, src/main/java/utils/StringUtils.java, src/main/java/webserver/HttpRequest.java, src/main/java/webserver/HttpRequestMapper.java, src/main/java/webserver/HttpRequestParser.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/test/java/utils/StaticFIleUtilsTest.java, src/test/java/webserver/HttpRequestParserTest.java
httpRequest의 method, url, header, body를 파싱하고 VO객체에 저장.
파싱한 값을 토대로 request header를 출력하고 정적파일에 대한 요청을 처리.
많은 분들이 spring mvc 구조와 비슷하게 구성을 해나가고 계신데 구조에 대한 이해 부족으로 인해 어떤 방식으로 클래스 분할을 하고 패키징을 할 지 매우 혼란스러움. 일단은 기능요구에 맞게 요청을 처리할 수 있도록 하고 이후에 리팩토링을 통해 구조를 잡아보도록 해야겠다.
=> [조형준] step-1 index.html 응답

README.md, src/main/java/controller/UserController.java, src/main/java/support/ControllerResolver.java, src/main/java/support/DefaultInstanceManager.java, src/main/java/support/InstanceInitializer.java, src/main/java/support/InstanceManager.java, src/main/java/support/annotation/Container.java, src/main/java/support/annotation/Controller.java, src/main/java/utils/ClassListener.java, src/main/java/webserver/Header.java, src/main/java/webserver/HttpHandler.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/request/HttpRequest.java, src/main/java/webserver/request/Query.java, src/main/java/webserver/response/MIME.java, src/test/java/utils/ClassListenerTest.java, src/test/java/webserver/HttpRequestTest.java, src/test/java/webserver/RequestHandlerTest.java
- 다양한 MIME에 대응하여 웹 페이지가 이를 처리할 수 있도록 개선하였다.
- 서버의 다양한 인스턴스를 검색하고 관리할 수 있는 관리자 객체와 해당 초기화 메소드를 개선하였다.
- MIME 타입을 다양하게 구성하기 위해 map 자료 구조형을 일급 컬렉션으로 취급하여 이를 사용하고 있다. 이외에도 enum 클래스를 사용하는 방법과 단순하게 static final String으로 사용하는 방법이나, 미쳐 생각하지 못한 다른 방법이 있는지, 해당 방식의 장점과 단점이 무엇인지 햇갈린다. 해당 설계 방식에 대해 공부할 필요성이 있을 것 같다.
=> [박제현] step-3 다양한 컨텐츠 타입 지원

src/main/java/annotation/RequestMappingHandler.java, src/main/java/controller/Controller.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpResponse.java, src/main/java/http/HttpStatus.java, src/main/java/util/FileUtils.java, src/main/java/util/StringUtils.java, src/main/java/webserver/RequestHandler.java, src/main/resources/templates/user/form.html, src/test/java/annotation/RequestMappingHandlerTest.java, src/test/java/controller/ControllerTest.java, src/test/java/http/HttpRequestTest.java, src/test/java/util/FileUtilsTest.java, src/test/java/util/StringUtilsTest.java
- http header 파싱 오류 수정 (localhost:8080이 localhost로 저장 되는 오류)
- body를 파싱해서 사용자 회원가입, 로그인 구현 (쿠키 미적용)
- 잘못된 uri 입력은 404 http method로 응답
- http status를 enum 타입 적용
- HttpRequest와 HttpRequest의 코드가 길어지고 있다. 단순히 코드가 길다고 역할 분리가 잘 되지 않은 건가? 역할 분리가 잘 되었다의 기준은 무엇인가?
많은 분들이 애노테이션을 만들고 있는 것 같다...
=> [한도현] step-4 POST로 회원가입

README.md, src/main/java/annotation/GetMapping.java, src/main/java/controller/Controller.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/HandlerMapping.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/http/HttpStatus.java, src/main/java/webserver/http/request/HttpRequest.java, src/main/java/webserver/http/request/HttpRequestLine.java, src/main/java/webserver/http/request/Uri.java, src/main/java/webserver/http/response/HttpResponse.java, src/test/java/webserver/DispatcherServletTest.java, src/test/java/webserver/HandlerMappingTest.java, src/test/java/webserver/http/HttpRequestTest.java, src/test/java/webserver/http/UriTest.java
- 실제로 구현되어 있는 WAS와 비슷한 구조를 가져가고 싶었다. 따라서 Dispatcher Servlet 동작 원리를 이론적으로 학습하고 Dispatcher Servlet의 flow를 그대로 반영하려고 노력했다.
- Spring에서 MVC 패턴을 사용할 때 Controller에 http method에 따른 어노테이션이 존재하는데, 해당 어노테이션에 속성값만 적어주면 자동으로 mapping되는 부분을 구현하고자 했다. 따라서 Controller 클래스를 만들고 요청 경로에 맞는 GET API를 호출해주도록 구현했다.
- 이전에 실습을 통해 학습했던 Java Reflection 사용
- 동적으로 인자 받아서 메소드 호출해주기 위해 MethodType, MethodHandle 객체 활용
- 클라이언트의 요청에 대한 테스트는 어떻게 작성해야할 지 몰라서 테스트 코드를 작성하지 못했다. 직접 http request를 날려봄으로써 정상적으로 코드가 동작하는지 확인했는데, 이 부분에 대해서 테스트가 가능한지, 가능하다면 어떤 방식으로 해야할지 더 알아 보아야겠다.
- Dispatcher Servlet에서 요청과 응답에 대한 객체를 만드는데 책임을 불필요하게 많이 주는건지 고민이 된다. 실제 request, response에 대한 처리는 정확하게 어느 곳에서 동작하는 지 확인 후 그대로 방식을 차용하고 싶다.
- 실패하는 경우에 따라서 http status code는 만들어두었지만 해당 부분은 정상적으로 동작하지 않는다. custom Exception을 만들어서 dispatcher servlet에서 예외 처리를 해주려고 …
=> [최규현] step-2 GET으로 회원가입

README.md, gradlew, src/main/java/utils/StringUtils.java, src/main/java/webserver/Main.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/http/Headers.java, src/main/java/webserver/http/HttpMethod.java, src/main/java/webserver/http/HttpStatusCode.java, src/main/java/webserver/http/request/HttpRequest.java, src/main/java/webserver/http/request/RequestLine.java, src/main/java/webserver/http/request/Uri.java, src/main/java/webserver/http/response/HttpResponse.java, src/main/java/webserver/http/response/ResponseHandler.java, src/main/java/webserver/service/FileService.java, src/test/java/webserver/FileServiceTest.java, src/test/java/webserver/HeaderTest.java, src/test/java/webserver/HttpRequestTest.java
- http://localhost:8080/index.html 로 접속했을 때 index.html 파일을 읽어 클라이언트에 응답.
- Http request header를 출력
- 기존 Thread 기반 코드를 Concurrent 패키지를 사용하도록 수정
- 공부한 내용 https://github.com/SeoSiun/be-was/wiki 에 정리
- assertAll을 이용해 테스트코드 작성
- 소켓이나 Concurrent 패키지 등 잘 사용해보지 않았던 개념들을 공부하고 적용하는데에 시간이 오래 걸린 것 같다.
- 기능 구현뿐만 아니라 확장성도 함께 고려한 구조를 구현하려고 하니 생각보다 너무 어렵다..
피어리뷰를 하다보니 수업때 배웠던 어노테이션, 리플렉션을 사용하여 구현하는 방법도 있던데 좀 더 공부해보고 적용해봐야겠다! 
- http에 대해 좀 더 공부해봐야할 것 같다..
=> [서시언] step-1 index.html 응답

src/main/java/service/UserService.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/model/Response.java, src/main/resources/templates/user/form.html
1. 현재 정적 파일을 찾는 것이 아니고, 서비스 로직에 존재하지 않는 경로의 요청이라면 404를 내보내도록 하였는데, 사실 이렇게 구현하기보단 각각 문제 상황에 대해 400번대 코드로 분할해서 처리해야 하나 싶다. 구현한다면 exception 처리를 해야하는데, 한 군데에서 통합해서 처리하는게 나을지, 아니면 각각에 대해 처리할지 고민된다.
2. service 로직으로 일부 옮겼음에도 RequestHandler가 여전히 많은 일을 하는 것 같기도 하다... controller를 추가해야 하나 고민된다.
post 끝에는 newline이 붙지 않는다는 것을 몰라 br.readline()을 시도해 계속 멈췄었는데, content-length를 이용해 읽어들이는 것으로 해결했다!
=> [정성태] step-4 POST로 회원 가입

src/main/java/db/Database.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/controller/UserSaveController.java, src/main/java/webserver/exceptions/BadRequestException.java, src/main/java/webserver/exceptions/ConflictException.java, src/main/java/webserver/http/HttpMethod.java, src/main/java/webserver/http/HttpRequest.java, src/main/java/webserver/http/HttpResponse.java, src/main/java/webserver/http/HttpStatus.java, src/test/java/webserver/controller/UserSaveControllerTest.java
- GET으로 회원가입 기능 구현
- URL Parameter 생략 시 Bad Request 응답
- 회원정보 미입력 시 Bad Request 응답
- 아이디가 중복되면 Conflict 응답
- 브라우저가 Request-URI를 인코딩하는 방식은 무엇인가
- Controller에서 발생한 예외를 어디에서 처리할지
- 서비스 로직 처리 역할을 Service로 분리할지
- ## 기타
- 처음부터 MVC 패턴을 적용하기보단, 이후 스텝을 진행하며 필요시 소프트웨어의 구조를 점진적으로 개선해 갈 계획입니다.
=> [김동철] step-2 GET으로 회원가입

README.md, src/main/java/controller/HomeController.java, src/main/java/model/HttpMethod.java, src/main/java/model/HttpRequest.java, src/main/java/model/HttpResponse.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/HandlerAdapter.java, src/main/java/webserver/HandlerMapping.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/ServletContainer.java, src/main/java/webserver/WebServer.java, src/test/java/model/HttpRequestTest.java
- Thread관련 Wiki 작성
- HttpRequest 클래스 생성 및 테스트 코드 작성
- Servlet Container의 구조에 맞게 클래스 생성
- Concurrent 패키지를 이용하여 스레드 관리
- request에 저장된 정보를 가지고 view 경로 생성
- step1의 시작이 관련 내용을 학습하고 구조를 생각하느라 많이 늦어졌다. 하지만 Step2부터 필요한 코드들을 어떻게 짜야할지 구상을 끝내 이후 과정들은 금방 진행할 수 있을 거라 생각한다.
- css나 js와 같은 정적 파일들은 별도의 폴더에 저장되어 있는데, 이를 어떻게 구분하여 가져올지 고민이다.
- 2번의 피어세션을 통해 먼저 진도를 많이 나가신 분들의 코드를 보았는데, 다들 정말 깔끔하게 짜셔서 실제 구현하는데 도움을 많이 받은 것 같다.
- 처음의 설계만 잘 한다면 리팩토링할 부분은 크게 없을거라 생각한다. 사실 WAS 자체가 이미 스프링 프레임워크에서 제공되고 있는 기능이기 때문에 정답이 정해진 설계를 구현만 잘하면 될 것이라 생각한다.
=> [김종원] Step-1 index.html 응답

src/main/java/controller/Controller.java, src/main/java/controller/HomeController.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/http/controller/ControllerMapper.java, src/main/java/webserver/http/controller/FrontController.java, src/main/java/webserver/http/controller/ViewResolver.java, src/main/java/webserver/http/message/HttpHeaderFields.java, src/main/java/webserver/http/message/HttpMethod.java, src/main/java/webserver/http/message/HttpRequest.java, src/main/java/webserver/http/message/HttpResponse.java, src/main/java/webserver/http/message/HttpStatus.java, src/main/java/webserver/http/message/URL.java, src/main/java/webserver/http/utils/Constant.java, src/main/java/webserver/http/utils/HttpConstant.java
- 자바 스레드, concurrent 패키지 학습
- [📖 Java Concurrency](https://github.com/mingulmangul/be-was/wiki/Java-Concurrency)
- 소켓 연결 스레드 생성 시 concurrent 패키지를 사용하도록 변경
- Thread(`thread.start(Runnable)`) ➡️ concurrent(`executor.execute(Runnable)`
- 정적 파일 응답 (`/index.html`로 접속 시 프로젝트 내 `index.html` 파일을 읽어와 응답)
- HTTP request 로그 출력
- HTTP request 파싱
- 파일 검색 후 읽기
- HTTP response 메세지 작성 후 클라이언트에게 응답
- 프로젝트 구조 개선
프로젝트 구조를 처음부터 최대한 확장성 있게 구현하려고 하다보니 고민이 많이 되어 시간이 오래 걸린 것 같다. 현재는 스프링 MVC의 구조를 참고하여 프론트 컨트롤러가 요청을 처리하는 다른 로직을 호출하는 구조로 구현하였다. 세부적인 기능은 아직 구현하지 않았는데, 앞으로 annotation과 reflection을 이용해 프로젝트 내의 컨트롤러와 메소드 정보를 읽고 url 매핑 정보를 찾을 수 있는 기능을 추가할 예정이다.
=> [권민아] step-1 index.html 응답

src/main/java/webserver/utils/ContentTypeResolver.java
- stylesheet 와 파비콘 등을 지원하기 위해 다양한 컨텐츠 타입을 지원
- jpg를 제외한 나머지 파일 타입에 대한 컨텐츠 타입 지원은 스텝 1에서 구현하여 이번 스텝에서는 jpg 및 jpeg 파일 컨텐츠 타입만 추가
=> [김동철] step-3 다양한 컨텐츠 타입 지원

src/main/java/controller/FileController.java, src/main/java/controller/ServiceController.java, src/main/java/db/Database.java, src/main/java/http/HttpParser.java, src/main/java/http/HttpUtil.java, src/main/java/model/Session.java, src/main/java/model/UserSession.java, src/main/java/service/SessionService.java, src/main/java/service/UserService.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/model/Response.java, src/test/java/service/UserServiceTest.java
규모가 어느 정도 커져서 어느 정도 리팩토링을 진행했다. 어디까지가 누구의 책임인지 구별하는 것이 어려웠지만, 한 번 구별하고 나니 각 코드가 훨씬 간결해진 것 같다.(근데 이게 맞게 한건진 조금 애매한거 같기도 하다... 일단 최대한 합리적으로 해봤다.) 다만, 슬슬 Controller가 늘어나는 상황을 생각하면 어노테이션을 써야 하는지 고민된다. 어노테이션을 쓰면 좋을 것 같기도 한데, 그에 대한 추가 로직이 들어가는 것도 사실이라 아직은 고민중이다. 더 서비스 로직이 많고 복잡해지면 사용할 수도 있을 것 같다.
=> [정성태] step-5 쿠키를 이용한 로그인

src/main/java/controller/UserController.java, src/main/java/model/User.java, src/main/java/support/ControllerResolver.java, src/main/java/support/InstanceInitializer.java, src/main/java/support/annotation/Container.java, src/main/java/support/annotation/ResponseStatus.java, src/main/java/support/exception/BadRequestException.java, src/main/java/support/exception/FoundException.java, src/main/java/support/exception/HttpException.java, src/main/java/support/exception/MethodNotAllowedException.java, src/main/java/support/exception/ServerErrorException.java, src/main/java/webserver/Cookie.java, src/main/java/webserver/HttpHandler.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/response/HttpResponse.java, src/main/java/webserver/response/HttpStatus.java, src/test/java/webserver/RequestHandlerTest.java
- 로그인 성공 여부에 따른 리다이렉션 분리
- 쿠키 구현, 로그인 쿠키 등록
- 쿠키 등록에 따른 테스트 코드를 작성할 방법을 생각하고 있다. 현재 테스트 코드는 요청, 반환 메세지에 집중하고 있어 실제 클라이언트 브라우저에서 작업하는 동작까지 테스트하기에는 어려움이 있다.
- 로그인 쿠키에 어떤 값을 써야 할지 고민하고 있다. 쿠키는 공개된 정보이기에 보안적으로 이를 보완할 방법을 찾아야 한다.
=> [박제현] step-5 쿠키를 이용한 로그인

src/main/java/container/Servlet.java, src/main/java/db/Database.java, src/main/java/lock/NamedLock.java, src/main/java/model/user/User.java, src/main/java/servlet/Servlet.java, src/main/java/servlet/domain/html/IndexServlet.java, src/main/java/servlet/domain/html/UserListServlet.java, src/main/java/servlet/domain/user/UserCreateServlet.java, src/main/java/servlet/domain/user/UserLoginServlet.java, src/main/java/session/SessionStorage.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/http/HttpRequest.java, src/main/java/webserver/http/util/HttpUtil.java, src/test/java/servlet/domain/user/UserCreateServletTest.java, src/test/java/servlet/domain/user/UserLoginServletTest.java, src/test/java/session/SessionStorageTest.java, src/test/java/webserver/http/HttpUtilTest.java
- 로그인 상태에 따라 index.html 동적으로 생성
- 로그인 상태에 따라 user/list.html 동작 처리
- 동시성 처리 부분 수정
- 현재 html 생성을 Servlet에서 해주고있다. 해당 방법은 Servlet에 너무 많은 역할을 지우기에 추후에 JSP와 같은 템플릿 엔진과 MVC 구조를 사용하면서 이젠 사용되지 않는 방법으로 알고있다. 아마 추후 요구사항에 템플릿 엔진을 사용하여 html을 만들어주는 요구사항이 나오지 않을까?.. 그때는 어떤 방식으로 변경해야할지 고민하며 템플릿 엔진 동작방식을 찾아봐야겠다.
- 기존에 회원가입 로직에서 Lock을 이용하여 동시성 처리를 해주고 있었는데, 스쿼드 세션과정에서 잘못된 로직이 존재함을 발견하였다. 멀티스레드 상황에서 유일한 Lock 저장소를 이용해야 제대로된 동시성 처리가 이루어지는데, 스레드마다 Lock 저장소를 새로 생성하여 제대로된 동시성 처리가 이루어지지 않고 있음을 확인했다. 해당 부분도 결국 TC가 제대로 작성되어 있지 않아서 문제를 발견하지 못했다고 생각한다. TC 작성시에 멀티스레드 상황에 대한 테스트도 작성하도록 하자.
=> [Step6] 동적인 HTML (#13)

src/main/java/utils/StringUtils.java, src/main/java/view/view/StaticView.java, src/main/java/view/view/View.java, src/main/java/view/viewResolver/StaticViewResolver.java, src/main/java/view/viewResolver/ViewResolver.java, src/main/java/webserver/ContentType.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/Header.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/request/HttpMethod.java, src/main/java/webserver/request/HttpRequest.java, src/main/java/webserver/request/RequestHeader.java, src/main/java/webserver/response/HttpResponse.java, src/main/java/webserver/response/HttpStatus.java
- HttpRequest class
+ Request를 처리하기 위한 클래스 구현
+ method는 enum으로 구현
+ Header는 map을 1급 컬레션으로 감싸서 구현
- HttpResponse class
+ Response를 처리하기 위한 클래스 구현
+ HttpStatus enum으로 구현
- View, ViewResolver
+ path에 맞는 file을 찾기 위한 viewResolver interface 구현
+ rendering을 담당할 View interface 구현
+ 정적 파일을 위한 StaticViewResolver, StaticView 구현
- Dispatcher class
+ request를 parameter로 받아 최종적으로 response 객체를 만들어 반환하기 위한 클래스
- StringUtils
+ 개행 문자 중복을 제거하기 위한 StringUtils 구현 
1. 도대체 어떻게 접근을 해야할까?
- 이런 http를 이론적으로만 공부했지 직접 구현하는 것에 대해 해본적이 없어서 어떻게 시작해야 하나 막막했다.
- 먼저 현재 주어진 코드를 다음과 같이 분석했다.
+ WebServer의 main 메소드에서 시작
+ 만약 실행 당시 argument가 주어졌다면 port를 해당 argument로 변경, 아니라면 default port 8080 사용
+ ServerSocket 객체를 생성하여, port 번호에서 클라이언트의 연결 요청을 기다린다.
+ while문을 이용해 계속해서 연결 요청을 받아드린다.
+ 연결 요청이 들어오면 listenSocket.accept()를 이용해 요청을 …
=> [이병찬] Step-1 index.html 응답

README.md, src/main/java/annotations/Controller.java, src/main/java/annotations/RequestMapping.java, src/main/java/controller/HomeController.java, src/main/java/controller/UserController.java, src/main/java/dto/UserDTO.java, src/main/java/model/ContentType.java, src/main/java/model/HttpMethod.java, src/main/java/model/HttpRequest.java, src/main/java/model/HttpResponse.java, src/main/java/model/HttpStatus.java, src/main/java/service/UserService.java, src/main/java/view/ModelAndView.java, src/main/java/view/ViewResolver.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/HandlerAdapter.java, src/main/java/webserver/HandlerMapping.java, src/main/java/webserver/ServletContainer.java, src/main/java/webserver/WebServer.java, src/main/resources/templates/404.html, src/test/java/model/HttpRequestTest.java
- HTTP Request & Response 구현
- HTTP Status, ContentType, Method 구현
- DispatcherServlet, HandlerMapping, HandlerAdapter 구현
- UserController 생성 후 create GET 접근 구현
- Controller, RequestMapping 어노테이션 구현
- 정적파일 접근 시 처리 가능하도록 구현
- 오류 시 404 페이지 및 에러 반환하도록 구현
- 리플렉션을 적용한 Controller 클래스를 찾고(여러 개 존재 시 모두 찾기) 그 안에서 URI에 매핑되는 메서드 찾도록 적용
- 최대한 Spring WAS와 구조를 동일하게 가져가고 싶어 학습 및 설계를 하다 오래걸렸던 것 같다.
- 현재 Create 후에 return 으로 "/"으로 돌아가며 200 Response를 요청하도록 처리했는데, 이렇게하니 정적파일들(css, js)가 user/app.js 등으로 잘못 요청하고 있다. 이부분은 사실 Step-3에서 구현하는 부분인데 create를 처리하다보니 한번에 구현하게 되어 Step-3에서는 이 에러를 잡는 부분으로만 진행할 생각이다.
- 실제 Spring의 동작 과정을 코드를 보며 이해는 했지만, 정확하게 이해했는지 확신할 수가 없었다. 피어세션 때 다른분들의 코드를 봐도 모두 구조가 달랐고 이해한 바가 달라(물론 정답은 없겠지만) 정석적인 구현이 어떤 것인지 알고싶었다.
- 특히 정적파일의 접근은 확장자 타입을 보고 접근하도록 했는데, 이 방식에 대해 개선할 수 있는 방법이 무엇이 있을지 고민중이다.
- …
=> [김종원] Step-2 GET으로 회원가입

src/main/java/controller/UserController.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpResponse.java, src/main/java/http/MIME.java, src/main/java/webserver/HandlerMapping.java, src/main/java/webserver/RequestHandler.java
* MIME enum 생성
* HttpRequest 와 HttpResponse 에 MIME 필드 추가
* HandlerMapping 에서 해당하는 핸들러를 찾지 못하면 null 반환 -> 정적파일 호출
* step-3 를 구현하고 redirect 를 조금 건드려봤는데 정적파일을 호출할 때 경로가 이상하게 설정되는 오류를 발견했다... step-4를 진행하면서 원인을 알아보고 해결해야겠다.
* 클래스 이름을 MIME 으로 하는게 맞을지 ContentType 으로 하는게 맞을지 고민된다.. 
* RequestHandler 의 run() 메서드 안에서 너무 많은 일이 일어나고 있다. 더 늦기전에 슬슬 리팩토링을 해야하지 않을까?
* 아직 HTTP 에 대한 이해가 많이 부족한 듯 하다..
=> [김재홍] step-3 다양한 컨텐츠 타입 지원

src/main/java/Main.java, src/main/java/constant/Uri.java, src/main/java/controller/RestController.java, src/main/java/dto/UserFormRequestDto.java, src/main/java/mapper/ResponseMapper.java, src/main/java/model/HttpHeader.java, src/main/java/model/HttpRequest.java, src/main/java/model/HttpResponse.java, src/main/java/model/RequestUri.java, src/main/java/model/enums/MIME.java, src/main/java/service/FileService.java, src/main/java/util/Parser.java, src/main/java/util/StringUtils.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/resources/templates/user/form.html, src/test/java/model/RequestUriTest.java, src/test/java/service/FileServiceTest.java, src/test/java/util/ParserTest.java, src/test/java/util/StringUtilsTest.java, src/test/java/webserver/RequestHandlerTest.java
- Content-Length로 body까지 읽도록 처리
- POST로 들어온 요청 회원가입처리
- 회원가입후 리다이렉트 되게
- ttf, woff 콘텐트 못읽어오는 현상 수정
- 나는 java를 application단으로 생각해서 개발했는데 피어리뷰하면서 DI, 싱글톤까지 개발한 것보고 내가 대충했나 생각이 들었다.
- Content-Legnth를 Integer로 파싱하는 과정에서 오류가 난 것인데 버퍼 오류인지 알고 삽질했다. 자동으로 trim 될 줄 앎..
- ttf, woff 파일 Scanner로 읽으니까 파일을 못읽었다. Files.readAllBytes로 읽으니 해결됐다. 앞으로 response body는 byte로 보내도록 하겠다. 기본적인 16진수, 8진수, 2진수 파일 등 공부해야 될 듯. 지식의 부족함을 느낌.
- 구현하고 며칠 뒤 pr 보내는 거라 기억이.. 잘... 나지.. 않음... 망각의 동물........
=> [박선미] step-4 POST로 회원 가입

src/main/java/annotation/RequestMappingHandler.java, src/main/java/controller/Controller.java, src/main/java/db/Session.java, src/main/java/db/SessionManager.java, src/main/java/http/Cookie.java, src/main/java/http/HttpHeader.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpRequestHeader.java, src/main/java/http/HttpResponse.java, src/main/java/http/HttpStatus.java, src/main/java/http/Mime.java, src/main/java/util/HttpUtils.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/ResponseHandler.java, src/main/java/webserver/WebServer.java, src/test/java/annotation/RequestMappingHandlerTest.java, src/test/java/controller/ControllerTest.java, src/test/java/db/SessionManagerTest.java, src/test/java/db/SessionTest.java, src/test/java/http/CookieTest.java, src/test/java/http/HttpHeaderTest.java, src/test/java/http/HttpRequestHeaderTest.java, src/test/java/http/HttpRequestTest.java, src/test/java/http/HttpResponseTest.java, src/test/java/util/HttpUtilsTest.java
- 쿠키, 세션, 세션 매니저 구현
- 처음 접속 시, 30분짜리 세션 생성
- 요청시 접근 시간 초기화
- RequestMapping의 메소드를 먼저 확인하고 정적 파일을 응답하도록 변경
- controller 싱글톤 삭제
- response 응답 간소화
- 예외처리를 어떻게 해야 깔끔하게 응답할 수 있을까
- 만약 controller 말고 service, repository를 사용한다면 controller에 주입해야 할 텐데, 어떻게 주입을 시키지
=> [한도현] step-5 쿠키를 이용한 로그인

src/main/java/container/BaseServlet.java, src/main/java/container/DispatcherServlet.java, src/main/java/container/LogInServlet.java, src/main/java/container/LogInSuccessServlet.java, src/main/java/container/LogInTestServlet.java, src/main/java/db/SessionManager.java, src/main/java/parser/GetParser.java, src/main/java/util/HttpUtil.java, src/main/java/util/PathList.java, src/main/java/webserver/HTTPServletRequest.java, src/main/java/webserver/HTTPServletResponse.java, src/main/java/webserver/Mime.java
세션을 활용해서, 좀 더 보안적으로 유리한 코드를 설계합니다.
클래스들의 기능이 적절한가 잘돌아가더라도 나은 코드를 어떻게 하면 작성가능한지
=> [이용재] step-5 쿠키를 이용한 로그인

README.md, src/main/java/common/enums/ResponseCode.java, src/main/java/common/http/Cookie.java, src/main/java/common/http/HttpRequest.java, src/main/java/common/http/HttpResponse.java, src/main/java/common/http/RequestBody.java, src/main/java/common/http/RequestLine.java, src/main/java/common/http/Uri.java, src/main/java/common/wrapper/Cookies.java, src/main/java/common/wrapper/Headers.java, src/main/java/common/wrapper/KeyValuePair.java, src/main/java/common/wrapper/Queries.java, src/main/java/common/wrapper/SetCookies.java, src/main/java/controller/Controller.java, src/main/java/db/Database.java, src/main/java/model/User.java, src/main/java/service/UserService.java, src/main/java/session/UserSessionManager.java, src/main/java/utils/HttpRequestUtils.java, src/main/java/utils/HttpResponseUtils.java, src/main/java/webserver/Dispatcher.java, src/main/java/webserver/ViewResolver.java, src/test/java/utils/HttpRequestUtilsTest.java
1. 로그인을 구현했습니다.
- 세션 매니저 클래스를 만들었습니다. 이 클래스는 세션을 생성하고 조회할 수 있습니다. 로그인 시 UUID를 생성한 후 세션 저장소에 <세션ID>: <User>를 삽입합니다.
- 로그인 실패 시 실패 화면으로 넘어가도록 구현했습니다.
2. 쿠키를 구현했습니다.
- 클라이언트의 로그인 상태를 유지시키기 위해 쿠키를 구현했습니다. 
- 쿠키 클래스에는 Expries, Max-Age 등 다양한 Attributes가 필드로 존재해야하지만, 과제 수행에 필수적인 요소만 고려하여 cookie-name, cookie-value, path 만 가지도록 구현했습니다.
- 로그인 시 세션이 생성되고 세션 ID를 Response의 Set-Cookie로 전달하도록 했습니다.
1. 이전 스텝에서 추상 클래스인 KeyValuePair를 만들어둔 덕분에 Cookies 클래스 역시 상속으로 구현할 수 있었습니다. 그리하여 KeyValuePair를 상속 받는 클래스가 3개로 늘어났고 이들을 패키지로 묶어서 분리할 필요성을 느꼈습니다. 묶고 난 후 패키지명을 어떻게 해야할지 고민했습니다.
2. 세션을 저장해두기 위해 CuncurrentHashMap을 사용했습니다. 처음에는 HashMap을 사용했었으나, 동기화를 지원하지 않는 HashMap은 멀티 스레드 환경에 사용하기 적합하지 않다는 것을 배우고 CuncurrentHashMap을 사용하기로 했습니다.
=> [이준호] step-5 쿠키를 이용한 로그인

src/main/java/controller/HomeController.java, src/main/java/controller/HttpController.java, src/main/java/controller/JoinController.java, src/main/java/controller/LoginController.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpRequestParser.java, src/main/java/http/HttpResponse.java, src/main/java/http/HttpSession.java, src/main/java/webserver/FrontController.java, src/main/java/webserver/RequestHandler.java, src/test/java/controller/HomeControllerTest.java, src/test/java/controller/JoinControllerTest.java
로그인 시 쿠키에 세션id를 설정
생성된 세션id를 User객체와 함께 concurrentHashMap에 저장
세션 지속시간을 어떻게 구현할 지
http에 Map으로 관리하는 값이 많은데 일급 컬렉션이나 별도 객체로 분리할 지 고민
=> [홍선기] step-5 쿠키를 이용한 로그인

src/main/java/controller/UserController.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpResponse.java, src/main/java/util/Parser.java, src/main/java/webserver/RequestHandler.java, src/main/resources/templates/user/form.html
* HttpResponse 302Header 구현
* 응답 시작줄과 Location 으로만 구성함. Location 은 "/index.html" 로 지정해두었으나 추후에 Location 인자를 넘겨받도록 수정 예정.
* "/" 로 접근 시 "/index.html" 호출하도록 Parser 클래스 parsePathFromUrl 메서드에서 구현.
* form.html 에서 회원가입을 POST 메서드로 수행하도록 수정.
* HttpRequest 클래스에 body 추가 및 body 에서 파라미터 추출하는 메서드 구현.
* 컨트롤러에서 HTTP request 의 body 에서 회원정보를 추출하여 회원가입.
* HttpResponse 에서 redirect 를 호출할 때 MIME 타입으로 html 을 넘겨받고 있는데 꼭 필요한 부분일까? 좀 더 간결하게 구현할 수 있을거같다.
* HttpRequest 에서 body 가 쿼리스트링형태가 아닌 경우엔 어떤식으로 처리해야할까 고민된다.
=> [김재홍] step-4 POST로 회원 가입

README.md, src/main/java/application/presentation/UserController.java, src/main/java/common/annotation/Controller.java, src/main/java/webserver/http/Http.java, src/main/java/webserver/http/response/HttpResponse.java, src/main/java/webserver/http/response/process/ApplicationProcessStrategy.java
- 다양한 컨텐츠 타입을 지원하도록 개선 
- redirect 기능 구현
- 이전 단계에서 이미 구현해놔서 이번 미션은 쉽게 해결했다!!
=> [최윤식] step-3 다양한 컨텐츠 타입 지원

src/main/java/controller/UserController.java, src/main/java/model/ContentType.java, src/main/java/model/HttpResponse.java, src/main/java/model/HttpStatus.java, src/main/java/model/User.java, src/main/java/service/UserService.java, src/main/java/view/ModelAndView.java, src/main/java/webserver/HandlerAdapter.java, src/test/java/controller/UserControllerTest.java
- Step2에서 먼저 구현했던 컨텐츠 타입 지원에서 추가적으로 버그가 발생했던 ttf, woff타입 지원
- Redirect시 잘못된 url로 컨텐츠들로 요청을 보내는 오류 해결
- Redirect시 3xx로 응답 보내도록 수정
- 주말부터 계속 응답 위치가 이상해서 어떤 문제인지 찾고 있었는데, 300번대 응답 시 Location과 Status를 모두 설정해야 정상적으로 동작한다는 것을 팀원분을 통해 알게되었다.
- PRG 패턴에 대해서도 공부를 해야할 것 같다.
- 테스트 코드를 아직도 만들지 않았는데, 어디서 테스트가 필요할지 정말 모르겠다. Step4 시작전에 테스트를 구현해야겠다.
- 이번 step에 적합한 주제는 아니였지만 redirect의 동작방식에 대해 잘 알게 되었다.
=> [김종원] Step-3 다양한 컨텐츠 타입 지원

src/main/java/db/SessionDatabase.java, src/main/java/webserver/controller/ControllerHandler.java, src/main/java/webserver/controller/UserController.java, src/main/java/webserver/http/HttpResponse.java, src/main/java/webserver/http/Session.java, src/main/resources/templates/user/form_failed.html, src/test/java/test.java
- [로그인] 메뉴를 클릭하면  /user/login.html페이지로 이동
- 입력한 id와 password와 동일한 user가 db에 저장되어 있으면 /index.html로 리다이렉트
- 로그인에 실패하면 login-failed.html로 이동
- 로그인 시 Cookie에 sessionId가 포함되어 있지 않으면 Response객체에 Set-Cookie헤더에 sessionId를 추가하여 전달
- sessionId와 userId를 맵핑하는 sessiondatabase추가
- 회원가입시 이미 존재하는 id로 가입 시도시 form-failed.html로 이동
- "userId", "password"와 같은 문자열을 상수화 시킬지 고민하였다.
- session을 클래스를 따로 만들어 멤버변수로 sessionId를 갖도록 할지 고민하였다.
=> [김우혁] step-5 쿠키를 이용한 로그인

README.md, src/main/java/db/Database.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/controller/Controller.java, src/main/java/webserver/controller/ControllerResolver.java, src/main/java/webserver/controller/FileController.java, src/main/java/webserver/controller/UserSaveController.java, src/main/java/webserver/controller/file/FileController.java, src/main/java/webserver/controller/user/UserLoginController.java, src/main/java/webserver/controller/user/UserSaveController.java, src/main/java/webserver/exceptions/LoginFailException.java, src/main/java/webserver/http/Cookie.java, src/main/java/webserver/http/HttpParameters.java, src/main/java/webserver/http/HttpRequest.java, src/main/java/webserver/http/HttpResponse.java, src/main/java/webserver/session/Session.java, src/main/java/webserver/session/SessionManager.java, src/test/java/webserver/controller/file/FileControllerTest.java, src/test/java/webserver/controller/user/UserLoginControllerTest.java, src/test/java/webserver/controller/user/UserSaveControllerTest.java, src/test/java/webserver/http/HttpRequestTest.java, src/test/java/webserver/http/HttpResponseTest.java, src/test/java/webserver/utils/HttpRequestCreateUtil.java
- 세션 기반 로그인 기능 구현
- 요청을 처리할 컨트롤러를 결정하는 Controller Resolver 추가
- HTTP 요청 메시지의 Cookie 헤더에는 키-값 쌍의 데이터만 존재하는지(Set-Cookie 헤더의 Secure, HttpOnly와 같은 속성처럼 키-값 쌍이 아닌 데이터가 존재하는지)
- 스텝을 진행하며 적어놓은 고민사항들이 맥북 기기를 변경하면서 휘발되었습니다🥲
=> [김동철] step-5 쿠키를 이용한 로그인

README.md
- 기존에는 `Files.probeContentType(path)`를 사용해 MIME Type을 구했는데, 이 방식의 경우 모든 파일을 지원하게 되므로 특정 확장자만 지원할 수 있도록 MimeType enum을 별도로 만들어 사용했다.
- **확장자(.jpg, .jpe, .jpeg)를 동일하게 처리하는 방법**
여러 확장자를 동일하게 처리하기 위해 MimeType에 Set로 여러 확장자 타입들을 넣어 검사해 해결했다.
- Step-1에서 이미 Mime 타입을 지원하도록 구현해 놓아서 변경하는데 오래 걸리지 않았다.
- Step-2 PR에서 실수로 Step-4까지 진행한 것을 PR해버렸다.. Step-3, 4 는 PR용 브랜치로 PR 해야될 것 같다.
=> [신동우] Step-3 다양한 컨텐츠 타입 지원

src/main/java/controller/Controller.java, src/main/java/controller/SignUpController.java, src/main/java/model/User.java, src/main/java/webserver/FrontController.java, src/main/java/webserver/HttpRequestMapper.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/exception/BadRequestException.java, src/main/java/webserver/exception/ConflictException.java, src/main/java/webserver/exception/NotFoundException.java, src/main/java/webserver/reponse/HttpResponse.java, src/main/java/webserver/reponse/HttpResponseStatus.java, src/main/java/webserver/request/HttpRequest.java, src/main/java/webserver/request/HttpRequestParser.java, src/main/resources/templates/user/form.html, src/test/java/controller/SignUpControllerTest.java, src/test/java/webserver/FrontControllerTest.java, src/test/java/webserver/RequestHandlerTest.java, src/test/java/webserver/request/HttpRequestMapperTest.java, src/test/java/webserver/request/HttpRequestParserTest.java
회원 가입 요청 post로 전환
body 값을 통해 회원가입 처리
Redirection 구현
Controller를 싱글턴 객체로 정의하고 매 번 생성하는 것을 막도록 하였음.
예외처리를 RequestHandler에서 처리 하고 있어 객체의 역할이 명확하지 않아 FrontController에 이를 위임하고 response를 보내주는 것으로 수정.
회원 가입시 중복된 아이디에 대한 예외처리.
response를 어디서 처리하는 것이 맞는지에 대한 고민으로 인해 특정 비즈니스 로직으로 파생된 값이 body에 들어갈 경우가 있다고 생각이 들어 요청이 성공적으로 처리 되었을 시에는 Controller에서 response를 설정하고 예외 발생 시에 FrontController에서 이를 감지해 response를 설정하도록 구성하였음.
=> [조형준] step-4 POST로 회원 가입

README.md, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/IndexPageController.java, src/main/java/webserver/controller/ControllerResolver.java, src/main/java/webserver/controller/IndexPageController.java, src/main/java/webserver/controller/file/FileController.java, src/main/java/webserver/controller/user/UserListController.java, src/main/java/webserver/controller/user/UserLoginController.java, src/main/java/webserver/controller/user/UserSaveController.java, src/main/java/webserver/http/HttpHeaders.java, src/main/java/webserver/http/HttpParameters.java, src/main/java/webserver/http/HttpRequest.java, src/main/java/webserver/http/HttpResponse.java, src/main/java/webserver/session/Session.java, src/main/java/webserver/session/SessionManager.java, src/main/java/webserver/utils/FileUtils.java, src/main/java/webserver/utils/HttpParametersParser.java, src/main/resources/templates/index.html, src/main/resources/templates/user/list.html, src/test/java/webserver/IndexPageControllerTest.java, src/test/java/webserver/controller/file/FileControllerTest.java, src/test/java/webserver/controller/user/UserListControllerTest.java, src/test/java/webserver/http/HttpRequestTest.java
- 로그인 상태인 경우, /index.html 에서는 사용자 이름이 표시되지만 페이지를 이동하면 사용자 이름이 표시되지 않는 문제가 있다. 요구사항은 만족했지만 해당 문제도 처리하고 싶다.
=> [김동철] step-6 동적인 HTML

README.md, build.gradle, src/main/java/constant/Uri.java, src/main/java/controller/RestController.java, src/main/java/db/Database.java, src/main/java/dto/LoginRequestDto.java, src/main/java/mapper/ResponseMapper.java, src/main/java/model/HttpHeader.java, src/main/java/model/HttpResponse.java, src/main/java/model/User.java, src/main/java/model/enums/MIME.java, src/main/java/service/FileService.java, src/main/java/service/UserService.java, src/main/java/util/Parser.java, src/main/java/util/StringUtils.java, src/test/java/webserver/RequestHandlerTest.java
- 로그인 성공하면 세션 아이디 발급 후 쿠키에 추가되게 구현
- 로그인 성공하면 index.html, 실패하면 login_failed.html로 이동
- 점점 프레임워크의 존재 이유를 알아가는 중이다. 쿠키 설정 기능을 추가하려니 어디서 수행해야 할지 모르겠고 rest controller의 역할이 커지는 기분이다. 아무래도 requestHandler와 restcontroller 사이에 몇 개의 층이 더 있어야 될 것 같다. 리팩토링 시 고려할 것.
=> [박선미] step-5 쿠키를 이용한 로그인

src/main/java/annotation/RequestMappingHandler.java, src/main/java/controller/Controller.java, src/main/java/controller/UserResponse.java, src/main/java/converter/ModelConverter.java, src/main/java/db/SessionManager.java, src/main/java/http/HttpResponse.java, src/main/java/view/ViewResolver.java, src/main/java/view/Views.java, src/main/java/webserver/ResponseHandler.java, src/main/java/webserver/WebServer.java, src/main/resources/templates/index.html
- 세션 타이머를 스레드를 생성해서 사용하도록 변경
- 동적 HTML을 stringbuilder로 생성
- view를 어떻게 골라야할까..
- jsp가 필요해...
=> [한도현] step-6 동적인 HTML

src/main/java/annotation/RequestMapping.java, src/main/java/controller/UserController.java, src/main/java/http/HttpMethod.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpResponse.java, src/main/java/http/MIME.java, src/main/java/util/Parser.java, src/main/java/webserver/HandlerKey.java, src/main/java/webserver/HandlerMapping.java, src/main/java/webserver/RequestHandler.java, src/main/resources/templates/user/form.html
* 쿠키
* 로그인하면 HttpResponse 에 Set-Cookie 헤더를 추가하여 Cookie 를 설정하도록 하였다.
* 쿠키에는 세션ID 와 최상위경로("/")가 포함된다.
* 따로 클래스를 만들지 않고 HttpRequest 의 headers 에 추가하였다.
* 세션
* HttpSession 과 세션ID 별로 세션을 저장하는 SessionDatabase 생성
* 세션ID 는 쿠키 생성시 랜덤값으로 사용.
* UserController
* 회원가입시 중복처리 로직 추가
* 로그인시 회원 검증 로직 추가
* 로그인 성공시 세션 생성
* HttpRequest
* getCookie(), getSession() 메서드 추가
* getCookie(): headers 에서 쿠키값을 반환
* getSession(): 쿠키에서 sid 값을 추출하여 sid 에 해당하는 세션 반환
* handler 패키지 생성하여 Handler 관련 클래스 이동
* 예외 처리를 해야할 부분들이 꽤 많은데 어떤식으로 처리해야할까....?
* 쿠키와 세션에 대해 충분히 공부하지 않고 구현을 하려다보니 먼길을 돌아왔다....
=> [김재홍] step-5 쿠키를 이용한 로그인

README.md, src/main/java/application/common/StringUtils.java, src/main/java/application/presentation/UserController.java, src/main/java/application/service/UserMapper.java, src/main/java/application/service/dto/UserRequest.java, src/main/java/common/annotation/RequestBody.java, src/main/java/common/annotation/RequestMapping.java, src/main/java/webserver/http/request/HttpRequest.java, src/main/java/webserver/http/request/QueryParameter.java, src/main/java/webserver/http/response/HttpResponse.java, src/main/java/webserver/http/response/ResponseHandler.java, src/main/java/webserver/http/response/process/ApplicationProcessStrategy.java, src/main/resources/templates/user/form.html, src/test/java/webserver/WebServerTest.java
- “회원가입” 메뉴 폼을 통해서 회원가입을 할 수 있다.
- 회원가입을 POST로 구현
- 가입을 완료하면 /index.html 페이지로 이동한다.
- 현재 RequestMapping에 url 값을 설정하여 request target이 일치할 경우 해당 메서드로 처리하도록 구현이 되어 있다. 여기서 메서드에 따라 구분하는 기능을 추가해야 하는데 이 경우 GetMapping, PostMapping 등으로 분리를 해서 처리할지 아니면 RequestMapping에서 method 를 추가하여 검사할치 고민했다. 지금의 경우 어노테이션을 메서드별로 나누게 되면 어노테이션 검증 로직에서 각 어노테이션에 따른 분리를 해줘야하기 때문에 RequestMapping에 method 값을 추가하는 방식으로 구현했다. 뭐가 더 좋을까...
=> [최윤식] step-4 POST로 회원 가입

src/main/java/controller/LoginController.java, src/main/java/controller/SignUpController.java, src/main/java/db/Database.java, src/main/java/model/User.java, src/main/java/webserver/HttpRequestMapper.java, src/main/java/webserver/request/HttpRequest.java, src/main/java/webserver/request/HttpRequestParser.java, src/main/java/webserver/session/UserSession.java, src/main/java/webserver/session/UserSessionManager.java, src/test/java/webserver/FrontControllerTest.java, src/test/java/webserver/RequestHandlerTest.java, src/test/java/webserver/session/UserSessionManagerTest.java
- 로그인 로직을 구현하여 성공 시 index.html로, 실패 시 login_failed.html로 redirection
- SessionManager 클래스를 이용해 로그인 성공 시 유저 정보 세션에 저장, 쿠키를 통해 세션 아이디 전달
- 만료시간을 30분으로 설정하여 만료시간이 지난 세션 파기
-구성이 바뀌고 로직이 바뀔 때 마다 테스트 코드 또한 많이 바꾸는 상황이 발생하고 있다. 테스트 코드는 내부 로직이 변하더라도 영향을 받지 않도록 잘 작성하는 방법을 고민해봐야 할 것 같다.
-회원가입 시 동시성에 대한 처리를 ConcurrentHashMap 사용만으로 커버를 할 수 있는지 모르겠다. 이에 대해서 공부를 더 자세히 해봐야 할 것 같다.
-api 요청 하나 당 하나의 controller가 정의되고 각 컨트롤러 마다 request 유효성을 검사하는 비슷한 로직이 클래스를 너무 많이 차지 하고 있다. 이를 해결할 방법에 대해서 고민해 봐야 할 것 같다.
=> [조형준] step-5 쿠키를 이용한 로그인

README.md, src/main/java/application/common/StringUtils.java, src/main/java/application/infrastructure/LocalUserRepository.java, src/main/java/application/infrastructure/UserRepository.java, src/main/java/application/presentation/UserController.java, src/main/java/application/service/UserService.java, src/main/java/application/service/dto/LoginRequest.java, src/main/java/common/annotation/HttpResponse.java, src/main/java/webserver/http/Cookie.java, src/main/java/webserver/http/Headers.java, src/main/java/webserver/http/Http.java, src/main/java/webserver/http/Session.java, src/main/java/webserver/http/request/QueryParameter.java, src/main/java/webserver/http/request/RequestHandler.java, src/main/java/webserver/http/response/ApplicationProcessStrategy.java, src/main/java/webserver/http/response/ContentProcessStrategy.java, src/main/java/webserver/http/response/HttpResponse.java, src/main/java/webserver/http/response/ProcessStrategy.java, src/main/java/webserver/http/response/StaticContentProcessStrategy.java, src/main/java/webserver/http/response/TemplateProcessStrategy.java, src/main/java/webserver/http/response/process/ApplicationProcessStrategy.java, src/main/java/webserver/http/response/process/ContentProcessStrategy.java, src/test/java/webserver/WebServerTest.java
- 가입한 회원 정보로 로그인을 할 수 있다.
- 로그인이 성공하면 index.html로 이동한다.
- 로그인이 실패하면 /user/login_failed.html로 이동한다.
- 로그인이 성공할 경우 HTTP 헤더의 쿠키 값을 SID=세션 ID 로 응답한다.
- [로그인] 메뉴를 클릭하면 http://localhost:8080/user/login.html 으로 이동해 로그인할 수 있다.
- 세션을 싱글턴이나 static 중 어떤걸로 구현해야 할지 감이 잘 안잡힌다. 싱글턴은 안티 패턴이라는 말을 어디선가 들어서 싱글턴으로 구현하면 안되지 않을까 고민했지만 결국에는 싱글턴으로 구현했다.
- 세션과 쿠키의 차이점은 무엇일까? 쿠키에는 무슨 값들이 들어갈까?
=> [최윤식] step-5 쿠키를 이용한 로그인

README.md, src/main/java/db/Sessions.java, src/main/java/db/Users.java, src/main/java/service/UserService.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/container/ControllerContainer.java, src/main/java/webserver/controllers/StaticFileController.java, src/main/java/webserver/controllers/UserCreateController.java, src/main/java/webserver/controllers/UserLoginController.java, src/main/java/webserver/http/Cookie.java, src/main/java/webserver/http/HttpRequest.java, src/main/java/webserver/http/HttpRequestParser.java, src/main/java/webserver/http/HttpResponse.java, src/main/java/webserver/http/HttpUri.java, src/main/java/webserver/http/Session.java, src/main/java/webserver/utils/StringUtils.java, src/main/resources/templates/user/create_failed.html, src/test/java/webserver/controllers/UserCreateControllerTest.java, src/test/java/webserver/controllers/UserLoginControllerTest.java
- Session 클래스 추가
- Cookie 클래스 추가
- 로그인 시 Session을 생성하여 user 정보를 담도록 구현
- 생성한 Session Id를 Set-Cookie에 담아 브라우저가 쿠키를 저장하도록 구현
- Session & Cookie 클래스의 구조/필드
- 테스트 범위
- DB 저장과 Service 구조
=> [정지영] step-5 쿠키를 이용한 로그인

src/main/java/controller/UserController.java, src/main/java/dto/UserDTO.java, src/main/java/model/ContentType.java, src/main/java/model/HttpMethod.java, src/main/java/model/HttpRequest.java, src/main/java/model/HttpResponse.java, src/main/java/model/HttpStatus.java, src/main/java/parser/BodyParser.java, src/main/java/view/ModelAndView.java, src/main/java/view/View.java, src/main/java/view/ViewResolver.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/HandlerAdapter.java, src/main/java/webserver/ServletContainer.java, src/main/java/webserver/WebServer.java, src/main/resources/templates/user/form.html, src/test/java/controller/UserControllerTest.java, src/test/java/model/ContentTypeTest.java, src/test/java/view/ModelAndViewTest.java
- POST 방식도 지원하도록 구현을 이미 해놓았기 때문에 html파일의 send방식만 변경
- UserDTO에 빌더패턴을 적용하여 method의 파라미터를 인식해 자동적으로 매핑할 수 있도록 구현하고자 노력
- viewResolver를 통해 modelAndView와 View의 책임 분리, response에 데이터를 넣는 작업을 view에서 하도록 변경
- request body를 파싱하는 클래스를 별도로 두어 컨텐츠 타입 별로 파싱 방식을 다르게 가져갈 수 있도록 구현
- 메서드의 파라미터를 가져오는 것 까지는 가능한데, 이 타입 안에 있는 필드들에게 request에서 받아온 정보를 어떻게 매핑해주어야 할지 고민이다.
- 책임을 최대한 분리하고자 노력했는데도, 스파게티 코드가 된 부분들이 있어(static 렌더링인데 html 과 home을 처리하는 등) 이 부분들에 대한 리팩토링을 좀 더 고민해봐야 한다.
- 리팩토링과 테스트 코드는 미리미리 해두어야 함을 알고 있지만, 하기도 어렵고 복잡하여 미루다가 고생한 것 같다.
- 구조 설계를 잘 하고 구현을 했다 생각했는데, 막상 코드를 다시 보니 마음에 들지 않는 부분들이 많아 구조를 수정하였다. 이때문에 리팩토링 및 코드 개선 과정에서 정말 다양한 오류가 발생했고, 막막했다. step5를 진행하면서는 logging에 좀 더 신경써서 에러 위치를 더 정확히 찾을 수 있도록 할 생각이다.
- 벌써 step7까지 끝내신 분들이 계시는데, 너무 여유롭게 진행한 것 같아 걱정이다.
=> [김종원] step-4 POST로 회원 가입

src/main/java/controller/LoginController.java, src/main/java/controller/SignUpController.java, src/main/java/controller/view/Index.java, src/main/java/controller/view/UserList.java, src/main/java/webserver/FrontController.java, src/main/java/webserver/HttpRequestMapper.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/request/HttpRequest.java, src/main/java/webserver/request/HttpRequestHeader.java, src/main/java/webserver/request/HttpRequestLine.java, src/main/java/webserver/request/HttpRequestParser.java, src/test/java/webserver/FrontControllerTest.java, src/test/java/webserver/RequestHandlerTest.java, src/test/java/webserver/request/HttpRequestMapperTest.java, src/test/java/webserver/request/HttpRequestParserTest.java, src/test/java/webserver/session/UserSessionManagerTest.java
-로그인 여부에 따른 동적 html 생성 및 반환
-쿠키에 담겨있는 세션 id를 통해 세션 정보 확인
-기능 요구사항이 늘어남에 따라 HttpRequest 객체의 요소들이 늘어나면서 내부 요소들을 객체로 감싸서 관리하도록 하였음
-StringBuilder를 이용해 동적 html을 생성하다 보니 index.html 파일이 필요가 없어지고 코드가 너무 길어지게 되어 템플릿 엔진처럼 구현하는 것도 고려해봐야할 것 같다.
-현재 이 was에서는 user와 관련된 session 정보만 저장하고 있어 ConcurrentHashMap의 key, value를  sessionId와 user,만료시간이 결합된 객체로 설정하고 있는데 여러 attribute를 갖는 객체를 value로 설정하는것이 적절해보임
=> [조형준] step-6 동적인 HTML

readme/step6.md, src/main/java/controller/Controller.java, src/main/java/controller/dto/UserResponse.java, src/main/java/controller/mapper/UserMapper.java, src/main/java/global/handler/GetHandler.java, src/main/java/global/handler/PostHandler.java, src/main/java/global/request/RequestMapper.java, src/main/java/global/response/ResponseEntity.java, src/main/java/global/util/HttpUtil.java, src/main/java/global/util/SessionUtil.java, src/main/java/model/Session.java, src/main/java/service/UserService.java, src/main/java/view/View.java, src/main/resources/templates/index.html, src/test/java/controller/ControllerTest.java, src/test/java/controller/dto/UserResponseTest.java, src/test/java/controller/mapper/UserMapperTest.java, src/test/java/global/handler/GetHandlerTest.java, src/test/java/global/handler/HandlerInterfaceTest.java, src/test/java/global/request/RequestMapperTest.java, src/test/java/global/util/HttpUtilTest.java, src/test/java/global/util/SessionUtilTest.java, src/test/java/view/ViewTest.java
- View를 어떤식으로 보여주는게 맞을까라는 고민이 컸다. html의 코드를 만지는 것이 부담스러워 java의 String Builder로 하드 코딩하는게 맞나 싶었지만, 다른 방법이 없어서 진행했다. 다른 분들의 코드를 참고해보니, dispatcher servlet을 구현했으면, 구현하기 수월했을 것이다. 설계 단계에서 더욱 신경 쓰자.
- 기존에는 SessionUtil에서 HashMap<String, User> 형태로 Session을 관리했다. 이는 확장성 면에서도 불리하고 SessionUtil을 싱글톤으로 관리하지 않아 리펙토링을 진행했다. Session 클래스를 생성하여 세션 id와 유저의 정보를 담는 해시맵과 만료시간을 필드를 갖게 했다. 
- 사용자의 list를 보여주는 api에서 인코딩이 되지 않는 현상이 존재했다. 이를 해결할 수 있는 방법을 찾아보고 있다.
- Throwable과 throws Exception의 차이점은?
Throwable은 Java에서 모든 예외와 오류의 최상위 클래스이다. throws Exception은 메서드 선언부에 사용되는 예약어로, 해당 메서드가 해당 예외를 호출한 측으로 던지는 것을 나타낸다.
=> [권기호] step-6 동적인 HTML

README.md, src/main/java/controller/Controller.java, src/main/java/db/SessionManager.java, src/main/java/http/Cookie.java, src/main/java/http/HttpRequest.java, src/main/java/http/HttpResponse.java, src/main/java/http/Session.java, src/main/java/view/MainPageOfLoginUser.java, src/main/java/view/MainPageView.java, src/main/java/webserver/ContentType.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/WebServer.java, src/main/resources/templates/index.html, src/main/resources/templates/user/form.html, src/main/resources/templates/user/login.html, src/main/resources/templates/user/login_failed.html, src/test/java/controller/ControllerTest.java, src/test/java/db/SessionManagerTest.java, src/test/java/http/SessionTest.java, src/test/java/webserver/HandlerMappingTest.java
- 동적인 HTML 구현
- 로그인 상태O
- 로그인 상태X
- 로그인 상태를 구분하여 페이지를 렌더링하기 위해 메인페이지에 대한 View 객체를 만듦
- View 객체에서 직접 StringBuilder로 하나하나 html을 만들어줬기 때문에 확장에 용이하지 않음
- html에서 header 같이 공통되는 부분은 분리하고 바뀌는 부분만 실제 템플릿 엔진처럼 적용을 해야할까 고려할 필요성이 생김
- 현재 미션에서 생각보다 주어진 요구사항이 없기 때문에 금방 구현할 수 있었음
- 다음 미션에서 게시판 CRUD를 해야하는데, 다시 한 번 View와 Controller 관련해서 대규모 수정 작업이 필요하지 않을까 싶음
- 다음 미션에서 요구사항을 구현하면서 리팩토링 할 예정
=> [최규현] step-6 동적인 HTML

README.md, src/main/java/annotations/DeclaredControllers.java, src/main/java/annotations/DeclaredViewPolicies.java, src/main/java/annotations/ViewPolicy.java, src/main/java/controllers/Controller.java, src/main/java/db/Database.java, src/main/java/service/LoginService.java, src/main/java/webserver/RequestHandler.java, src/main/java/webserver/WebServer.java, src/main/java/webserver/http/HttpResponse.java, src/main/java/webserver/session/Session.java, src/main/java/webserver/view/Model.java, src/main/java/webserver/view/ModelView.java, src/main/java/webserver/view/ViewPolicy.java, src/main/java/webserver/view/ViewResolver.java, src/main/resources/templates/index.html, src/main/resources/templates/qna/form.html, src/main/resources/templates/qna/show.html, src/main/resources/templates/user/form.html, src/main/resources/templates/user/list.html, src/main/resources/templates/user/login.html, src/main/resources/templates/user/login_failed.html, src/main/resources/templates/user/profile.html, src/test/java/controllers/ControllerTest.java
- **읽은 HTML 문서를 어떻게 동적으로 렌더링할 것인지**
JSP나 타임리프처럼 HTML 문서 안에 특정 태그나 속성을 통해 어떻게 렌더링할지 정할 수 있으면 편할 것이라고 생각했다. 이렇게 진행하다 보니 렌더링 규칙을 어디에 정의할지와 렌더링을 어떻게 진행할지가 고민이었다. 커스텀 태그 규칙을 자유롭게 정할 수 있으면 좋겠다고 생각해 ViewPolicy라는 Annotation을 만들고, ViewPolicy로 정의된 메소드들(태그 렌더링 규칙)에 따라 렌더링을 진행하는 방식으로 진행했다.
- **컨트롤러에서 Attribute 정보를 어떻게 추가할지**
기존에는 컨트롤러에서 응답할 페이지만 반환했으나, ViewResolver에서 화면을 구성하기 위해 Attribute들을 컨트롤러에서 추가할 필요가 생겼다. 이를 구현하기 위해 ModelView(Model: attribute 저장 + Path: 응답할 페이지 경로)를 사용해 값을 전달했다. Controller에서 ModelView에 Attribute들과 Path를 추가하면, ViewResolver는 ModelView를 바탕으로 페이지를 구성해 response의 body를 구성하도록 했다.
- **정규식 Regex를 어떻게 작성할지**
ViewPolicy 애너테이션이 요소로 regex String을 갖도록 만들었는데, regex를 작성하는 부분이 쉽지 않았다. 특히 반복적으로 출력하는 부분이 어려웠던 것 같다. regex101.com 등으로 regex를 테스트하면서 렌더링 정책들을 만들었다.
- **반복적인 출력을 어떻게 할 것인지**
사용자 리스트, …
=> [신동우] Step-6 동적인 HTML

README.md, src/main/java/webapp/controller/UserController.java, src/main/java/webapp/db/Database.java, src/main/java/webserver/http/message/HttpHeaderFields.java, src/main/java/webserver/http/message/HttpResponse.java, src/main/java/webserver/http/message/HttpStatus.java, src/main/java/webserver/resolver/ControllerResolver.java, src/main/java/webserver/session/Cookie.java, src/main/java/webserver/session/Session.java, src/main/java/webserver/session/SessionStorage.java
**로그인 기능 구현**
- 로그인 실패
1. `/user/login_failed.html`를 응답 (`401 Unauthorized`)
- 로그인 성공
1. `/index.html`로 이동
2. 세션 생성 및 저장
- `Session`: 세션은 세션 아이디(`UUID` 타입)와 유저 정보(`userId`)를 저장
- `SessionStorage`: 세션을 생성하고 저장
3. 세션 아이디를 쿠키에 담아 클라이언트에게 응답
- `Cookie` 클래스에 쿠키의 키와 밸류, 디렉티브를 저장
- 응답 헤더에 `Set-Cookie` 필드를 추가
=> [권민아] step-5: 쿠키를 이용한 로그인

docs/README6.md, src/main/java/controller/Controller.java, src/main/java/service/UserService.java, src/main/java/webserver/DispatcherServlet.java, src/main/java/webserver/SessionManager.java, src/main/java/webserver/http/request/HttpRequest.java, src/main/java/webserver/http/response/HttpResponse.java, src/main/resources/templates/index.html, src/main/resources/templates/user/form.html, src/main/resources/templates/user/list.html, src/main/resources/templates/user/login.html, src/main/resources/templates/user/login_failed.html, src/test/java/controller/ControllerTest.java, src/test/java/service/UserServiceTest.java
- 로그인 상태인 경우 /index.html에 사용자의 이름 표시
- 쿠키, 세션 이용해서 로그인 상태 확인
- 로그인 상태가 아닌 경우 /index.html에 로그인 버튼 표시
- 로그인 상태일 경우 http://localhost:8080/user/list 에서 사용자 목록을 출력
- http://localhost:8080/user/list 페이지 접근시 로그인하지 않은 상태일 경우 로그인 페이지(login.html)로 이동
- 로그인을 하고 sessionId가 생성되면 index.html로 리다이렉트가 되지 않는 문제가 발생했다. 여러 사람들과 오랜 시간을 고민한 끝에 sessionId로 유저를 찾을 때 request header의 Cookie에 해당하는 값을 가져와서 "sid="가 붙은 채로 유저를 찾아 유저가 null이 되는 문제가 발생한다는 것을 찾아냈다.
- null이 발생하는 조건을 잘 따져보는 연습을 해야겠다.
- 동적으로 어떻게 구현할지 고민을 하다가 JSP 처럼 html에 동적으로 바꿀 위치를 삽입하는 방식을 택했다.
=> [김정연] step-6 동적인 HTML

README.md, src/main/java/application/common/StringUtils.java, src/main/java/application/presentation/HomeController.java, src/main/java/application/presentation/UserController.java, src/main/java/application/service/UserService.java, src/main/java/common/annotation/HttpRequest.java, src/main/java/webserver/http/Cookie.java, src/main/java/webserver/http/Http.java, src/main/java/webserver/http/Session.java, src/main/java/webserver/http/request/HttpRequest.java, src/main/java/webserver/http/response/ApplicationProcessStrategy.java, src/main/java/webserver/http/response/ContentProcessStrategy.java, src/main/java/webserver/http/response/HttpResponse.java, src/main/java/webserver/http/response/TemplateProcessStrategy.java, src/main/resources/templates/index.html, src/main/resources/templates/user/list.html, src/test/java/webserver/WebServerTest.java
- 사용자가 로그인 상태일 경우 /index.html에서 사용자 이름을 표시해 준다.
- 사용자가 로그인 상태가 아닐 경우 /index.html에서 [로그인] 버튼을 표시해 준다.
- 사용자가 로그인 상태일 경우 http://localhost:8080/user/list 에서 사용자 목록을 출력한다.
- http://localhost:8080/user/list  페이지 접근시 로그인하지 않은 상태일 경우 로그인 페이지(login.html)로 이동한다.
- 구현시 템플릿 엔진처럼 태크를 찾아서 설정한 값에 따라 동적으로 변경해주는 기능을 구현할 것인지 아니면 요청별 html 페이지를 만들어서 반환할지 고민했다. 현재 일정상 전자는 힘들 것 같아서 후자로 구현을 완료했다.
- 로그인시 서비스단에서 예외를 던질지 boolean 값을 반환할지 고민하였다. 로그인을 요청한 정보와 유저의 정보가 일치하지 않을 경우는 로그인에서 예외가 아닌 것 같아서 boolean 값을 반환하도록 구현하였다.
=> [최윤식] step-6 동적인 HTML

src/main/java/application/infrastructure/LocalQnaRepository.java, src/main/java/application/infrastructure/QnaRepository.java, src/main/java/application/model/Qna.java, src/main/java/application/presentation/HomeController.java, src/main/java/application/presentation/QnaController.java, src/main/java/application/service/QnaService.java, src/main/java/application/service/dto/QnaWriteRequest.java, src/main/java/db/QnaDatabase.java, src/main/java/webserver/http/response/TemplateProcessStrategy.java, src/main/resources/templates/index.html, src/main/resources/templates/qna/form.html, src/main/resources/templates/qna/show.html
- index.html 하단에 글쓰기 버튼을 추가한다.
- 로그인한 사용자가 글씨기 버튼을 클릭하면 write.html 로 이동한다.
- 로그인하지 않은 사용자가 글쓰기 버튼을 클릭하면 로그인 페이지로 이동한다.
- write.html에서는 글의 본문을 입력할 수 있는 폼을 표시한다.
- 작성한 글의 제목을 index.html에서 보여준다.
- 로그인한 사용자가 글 제목 클릭시 세부 내용을 볼 수 있는 페이지로 이동한다.
- 로그인하지 않은 사용자가 글 제목 클릭시 로그인 페이지로 이동한다.
- 동적 html을 타임리프나 머스테치처럼 아름답게 구현하고 싶었지만 팀 프로젝트로 이제 넘어가야해서 그만 놓아주기로 결심했다. 팀프로젝트에서 여유가 생길 것 같지는 않지만 만약 여유가 생긴다면 리팩터링도 진행해야겠다.
=> [최윤식] step-7 게시판 기능 완성
